repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: trailing-whitespace
          - id: check-toml
          - id: debug-statements

    - repo: local
      hooks:
          - id: format
            name: format
            stages: [commit]
            language: system
            entry: make format
            types: [python]

          - id: mypy
            name: mypy
            stages: [commit]
            language: system
            entry: make mypy
            types: [python]

          - id: test
            name: test
            stages: [commit]
            language: system
            entry: make test
            types: [python]
